version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Berlin
- package-ecosystem: npm
  allow:
  - dependency-type: "production"
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 20
  assignees:
  - Excodibur
  versioning-strategy: increase